### ISSUE TITLE
Extendable Request

### ISSUE THREAD

**Issue by 1ma** [Nyholm/psr7#111]
I'm wondering if you would consider removing the `final` modifier from `Nyholm\Psr7\Request`.

I totally agree in making most classes final by default, but in the case of PSR-7 requests I have a tendency to extend them to model certain API requests, overriding the constructor so that the object knows how to construct itself from domain objects rather than HTTP specifics (such as verb, URI, headers etc.) Here's an example: https://github.com/1ma/dca/blob/master/src/Bitstamp/Request/BuyOrder.php

What are your thoughts regarding this use case?

**Comment by mahagr** [comment]
You can use a decorator instead of extending the classes:

See: 
https://github.com/getgrav/grav/blob/1.6/system/src/Grav/Framework/Psr7/ServerRequest.php
https://github.com/getgrav/grav/blob/1.6/system/src/Grav/Framework/Psr7/Request.php
https://github.com/getgrav/grav/blob/1.6/system/src/Grav/Framework/Psr7/Traits/ServerRequestDecoratorTrait.php
https://github.com/getgrav/grav/blob/1.6/system/src/Grav/Framework/Psr7/Traits/RequestDecoratorTrait.php
https://github.com/getgrav/grav/blob/1.6/system/src/Grav/Framework/Psr7/Traits/MessageDecoratorTrait.php

**Comment by Zegnat** [comment]
I personally am a huge fan of having classes [`final` by default](https://matthiasnoback.nl/2018/09/final-classes-by-default-why/) and find there are [lots of interesting reasons](https://ocramius.github.io/blog/when-to-declare-classes-final/) for doing so. See also the previous discussion on this matter when this library originally switched to using `final`: #31.

I think it is very unlikely we’ll be reverting back to extendable classes.
