### ISSUE TITLE
Body is always empty

### ISSUE THREAD

**Issue by bpedroza** [Nyholm/psr7#135]
**Version: 1.2.1**

**Steps to recreate:**
`$response = new \Nyholm\Psr7\Response(203, [], 'hello world');
var_dump($response->getBody()->getContents());
var_dump((string)$response);`

**Expectation:**
Both `var_dump` calls dump "hello world"

**Actual result:**
 Both `var_dump` calls dump "" (an empty string)

**Comment by Zegnat** [comment]
For that last one, I would expect a fatal error (Object of class Nyholm\Psr7\Response could not be converted to string). Only Stream objects can be cast to a string. And when I use `(string)$response->getBody()` it works for me (I get “hello world”.)

That one also describes one of our unit tests: [testCanConstructWithBody](https://github.com/Nyholm/psr7/blob/master/tests/ResponseTest.php#L85-L90). So I am not surprised that it works. Can you confirm that it works when you do not try to cast the entire Response object?

The first one is … just not how `getContents()` works. The method is not for reading the entirety of a Stream, casting to a string does that. The PSR-7 definition is very clear that it should only return “the remaining contents”. This is a bit of a tricky issue. In the case of the body Stream, there is none, because the cursor is already at the end of the message. Sadly there is no clear definition of where the cursor should end up when a Stream first gets created.

For more reading, there is #99 which will also link you to my research about the problem on the PHP-FIG mailing list, as well as a link to a proposal for fixing it.

**Comment by bpedroza** [comment]
Thanks for the response. I'll close as the other issue is already addressing my problem here.
