### ISSUE TITLE
withBody + getBody results in an empty body

### ISSUE THREAD

**Issue by rbaarsma** [Nyholm/psr7#150]
I have the following library code, which is implemented in another Symfony application with httplug and auto discovery.

```
// Both `$requestFactory` and `$streamFactory` are the same instance of `Nyholm\Psr7\Factory\HttplugFactory` (through auto discovery).

$request = $requestFactory->createRequest($method, $url);

$body = json_encode(['test' => 'test']);
$request->withBody($streamFactory->createStream($body));

echo (string)$request->getBody(); // empty string "" (!)
```

I've traced this problem to the `MessageTrait`, the `withBody` method (line 126), does this:

```
        $new = clone $this;
        $new->stream = $body;  // Note: `stream` is a PRIVATE property and that's probably why this does nothing.
```

If I change the code to this, it works as expected:
```
        $this->stream = $body;
        $new = clone $this;
```

What I don't understand is that nobody else runs into this problem ;)

My version of nyholm/psr7 is 1.2.1

**Comment by rbaarsma** [comment]
I'm baffled, but when I change my code to do this, it works

```
$request = $this->requestFactory->createRequest($method, $this->host.$url)
    ->withBody($this->streamFactory->createStream($body));

echo (string)$request->getBody(); // now returns the $body as expected!
```

I really did not expect php to see direct chaining differently than using a local variable in between.

In any case, I stlil think this is very werid behavior and my first code should work too or otherwise give some kind of comprehensible exception why I shouldn't do that.. 

I still don't understand why the two statements are different

**Comment by Zegnat** [comment]
Every time you call a method on an object, it actually returns a completely new object rather than updating the existing one. So when you call `$request->withBody(…)` this call returns a new instance of a Request object while the original object $request is unchanged.

By making sure you redefine the variable `$request` you can make sure you always have the latest created object ready to use. You can do this by either chaining the method calls (because the final output returned gets assigned to your variable) or by redeclaring the variable like so:

```php
$request = $requestFactory->createRequest($method, $url);

$body = json_encode(['test' => 'test']);
$request = $request->withBody($streamFactory->createStream($body));

echo (string)$request->getBody(); // empty string "" (!)
```

Note how I have updated line 4 of your example code to start with `$request`.

This is because PSR-7 objects are defined to be immutable. Meaning (in short) they cannot be changed after being created. To quote from the PSR-7 [definition of a Request object](https://github.com/php-fig/http-message/blob/f6561bf28d520154e4b0ec72be95418abe6d9363/src/RequestInterface.php#L20-L22):

> ```
>  * Requests are considered immutable; all methods that might change state MUST
>  * be implemented such that they retain the internal state of the current
>  * message and return an instance that contains the changed state.
> ```

You can read more about this on the PHP-FIG’s website for PSR-7, under “[Why value objects?](https://www.php-fig.org/psr/psr-7/meta/#why-value-objects)”.

I am closing this issue as there is nothing here for this library to address. But if you have any follow-up questions, feel free to post them as I am happy to answer them :)
