### ISSUE TITLE
Make message classes final

### ISSUE THREAD

**Issue by Nyholm** [Nyholm/psr7#31]
From https://github.com/guzzle/psr7/pull/158#issuecomment-376237838

> I'm pretty confident that I will propose making all message classes in this project final if we ever hit a 2.0 version.
> 
> Reason: HTTP messages are represented as value objects, implementing an interface. From this point I don't see any valid use cases for extending the message classes.

FYI @sagikazarmark

**Comment by schnittstabil** [comment]
Please, do not.

> Reason: HTTP messages are represented as value objects, implementing an interface. From this point I don't see any valid use cases for extending the message classes.

Lack of knowledge is a wobbly basis for decisions, isn't it?

Let's assume `ServerRequestInterface` was not defined from the beginning, and all messages are final.
Now, someone comes up with that idea, and wants to implement it - like PSR-7 does:
> * [`interface ServerRequestInterface extends RequestInterface`](https://github.com/php-fig/http-message/blob/1.0.1/src/ServerRequestInterface.php#L43)
> * [`class ServerRequest extends Request implements ServerRequestInterface`](https://github.com/Nyholm/psr7/blob/0.3.0/src/ServerRequest.php#L16)

... which is not possible because of `final class Request` :unamused:

**Comment by sagikazarmark** [comment]
I'm sorry, I don't get your reasoning.

I've seen a few attempts to extend message classes and in my humble opinion they were all bad ideas trying to add something to the HTTP messaging layer that simply didn't belong there.

Even when there are cases when you want to add something custom to the message layer, there are better ways than extending*. PSR-7 provides you interfaces which you can implement and wrap other messages if necessary.

[Decorators](https://github.com/php-http/message/tree/master/src/Decorator) are a good example of that.

* I don't really like using that word in this context as those other ways are kind of "extensions" too. The point here is to avoid abusing inheritance for extension.

**Comment by sagikazarmark** [comment]
I think you are missing my point. I didn't say that PSR-7 cannot be extended, I said inheritance shouldn't be abused for that. It unfortunately happens in the PHP world all the time.

> PSR-7 authors believe that `ServerRequestInterface` extends `RequestInterface` is a good idea

Yes, because inheritance has a meaning there. It says the server request is still just an HTTP request with some server specific stuff. But it's still a plain HTTP request.

> Lack of knowledge is a wobbly basis for decisions, isn't it?
> Making them final means to throw the baby out with the bath water.
> Let's assume ServerRequestInterface was not defined from the beginning, and all messages are final.

I mean literally: what's the reasoning here.

> Another example are Mock objects, which become really cumbersome with final classes.

Why on earth would you mock HTTP messages? They are value objects, there isn't really a behaviour that you need to verify. It doesn't matter which methods are called if you want to check object equality. So again: why would you want to mock?

> which bad ideas are you want to prevent?

Leaking application logic into the HTTP message layer is a common thing I see. Talking about ApiRequests, LocalRequests (working without actual HTTP involvement).

> And why do final outweigh the disadvantages?

As I mentioned above: thanks to the interface you are perfectly in control of what happens: you can decorate messages for instance. I'm against inheritance which is a form of extension. There is time and place for that. But usually when inheritance involves value objects that's at least a break of SRP.

**Comment by schnittstabil** [comment]
Sorry, I do not understand your reasoning either. On the one hand you say:
> Yes, because inheritance has a meaning there. [`ServerRequestInterface` extends `RequestInterface`]

On the other hand you say:
> I don't see any valid use cases for extending the message classes.

But, that also means: you propose to make `Request` final! Which breaks the implementation of this project:
> [`class ServerRequest extends Request ...`](https://github.com/Nyholm/psr7/blob/0.3.0/src/ServerRequest.php#L16)

---
> Why on earth would you mock HTTP messages?

It seems, you are not very familiar with mocking. The _system under test (sut)_ is typically different from the _mock_:

```php
// does not work with final(!)
$mock = $this->getMockBuilder(ServerRequest::class)
             ->setMethods(['getAttribute'])
             ->getMock();
$mock->expects($this->once())
     ->method('getAttribute')
     ->with($this->equalTo('something'));

$sut = new RequestHandler();
$res = $sut->handle($mock);
$this->assertEquals(200, $res->getStatusCode());
```

---
> It doesn't matter which methods are called if you want to check object equality.

Btw, PSR-7 Messages are not that kind of _value objects_. PHP is not Java, for most PSR-7 implementations the following holds:
```php
// for example:
$res = new Response(200)
$res2 = $res->withStatus(400)->withStatus(200);

// We cannot check object equality of PSR-7 Messages using equals() or similar, all we can do is:
$res === $res2 //=> false
```
_value object_ in this case just means _immutabile objects_. And even that does not hold in the strict sense for PSR-7, because of because of `getBody()` etc.

**Comment by schnittstabil** [comment]
> But, that also means: you propose to make Request final! 

@sagikazarmark  Ah, sorry, I see you already figured that out at https://github.com/Nyholm/psr7/pull/32#issuecomment-378049481

**Comment by sagikazarmark** [comment]
> But, that also means: you propose to make Request final!

Honestly, I think that has very little relevance. You should rely on the contract, where the inheritance expresses a connection between the two types of requests.

> It seems, you are not very familiar with mocking.

Again: how is this an argument?

IMHO your code sample shows an anti-pattern: you shouldn't mock value objects. (Not to mention that you mock an implementation, instead of an interface?????) The goal is to make sure that your function returns an object with the desired properties. The way it is achieved is almost irrelevant. 

Regarding object equality: does a request have the same headers as the other? Same body?...etc. Then they are equal...and your test can pass (or fail).

I don't really see this conversation going anywhere, especially because things are getting personal, so I'm outta here.

**Comment by schnittstabil** [comment]
> Not to mention that you mock an implementation, instead of an interface?????

Do you _know_ guzzle? Just open an arbitrary test of the project you contribute, and you will see [tests like that](https://github.com/guzzle/guzzle/blob/c9615e7a872f18f63970b558f2555697f03e7803/tests/RedirectMiddlewareTest.php#L31-L40):

```php
    public function testIgnoresWhenNoLocation()
    {
        $response = new Response(304);
        $stack = new HandlerStack(new MockHandler([$response]));
        // ...
        $this->assertEquals(304, $response->getStatusCode());
    }
```

@sagikazarmark FYI, the mock (`$response`) is a concrete implementation. It should be obvious, but for clarification:
1. `Response` is **not** an interface, it is a concrete implementation
2. the mock is set up via its constructor to return the status code `304`

**Comment by Nyholm** [comment]
Michael, I’ll stop you right there. Mark is the person who done all the work on Guzzle the last year. 

Also, the test you show is using a concrete class. Not a mock. 

I’ve not seen any argument based on computer science or good software practice that says that they should NOT be final. I’ve only heard “it will be easier to mock”. And Michaels latest code example (and Marks arguments) shows that you should not mock requests and responses. 

I’m happy to continue the discussion if arguments are based on software design. One can not attack other people and question their knowledge. If this continues I’ll lock the thread.

**Comment by schnittstabil** [comment]
> Also, the test you show is using a concrete class. Not a mock.

Sorry, but why is it not a mock? Because it is not created via a framework? You may notice the expression `new MockHandler([$response])` as well. As a `MockHandler` _handles_ mocks, I do not see your point...

**Comment by Nyholm** [comment]
```
// This is not a mock, it is the real object
$request = new Request();

// This is a mock or a "fake" version of a class
$request = $this->getMockBuilder(Request::class)->getMock();
```

The MockHandler is just a handler that help you write tests.

**Comment by schnittstabil** [comment]
@Nyholm As you said, you want to discuss on arguments, I take you at your word:

```php
$request = $this
            ->getMockBuilder(Request::class)
            ->setConstructorArgs(['GET', 'https://foobar.example'])
            ->setMethods(null)
            ->getMock();
```

Is the above `$request` a mock, or not? You just gave two examples without explanation. How do you distinguish _real objects_ from _mock objects_? Btw, both are objects, and both are _real_, aren't they?
Please take into account, that the above `$request` object behave the same as an object created via `new Response('GET', 'https://foobar.example')`.

---

> The MockHandler is just a handler that help you write tests.

So the name has nothing to do with mocks? Are you sure? As far as i know the MockHandler returns mocks :confused:

**Comment by Nyholm** [comment]
I tried to give you some comments in my code snippet. 

> How do you distinguish real objects from mock objects?

The point of mocks is that other classes should not be able to see the difference. You, that write the tests, you create mocks because you want to override a behavior. You can find more about mocks and why in the [PHPUnit documentation](https://phpunit.de/manual/current/en/test-doubles.html)

> Btw, both are objects, and both are real, aren't they?

Yes both are objects. 

> Please take into account, that the above $request object behave the same as an object created via new Response('GET', 'https://foobar.example').

Yes it does. 

> So the name has nothing to do with mocks? Are you sure?

Im not sure about the implementation of this specific class. It is a real class, not a mock, and I assume it is used to ease testing. 

-------------

The point Mark is making is that you do not need to "override a behavior" for value objects. Since they are just getters and setters. They just hold a value.

**Comment by ncou** [comment]
just a silly question, I am not totally familiar with the php pattern. but what is the best way to use the *futur* final classes when you want to add a bunch of helper functions for the Response object or the ServerRequest ?

**Comment by ncou** [comment]
Thank you, i was thinking to use something similar => create a new classe with a delegate noted as private properties, but use a __call method to redirect all the methods.

something like this (with perhaps a check to throw an execption if the method does not exist) : 

```php
public function __call($func, $args)
    {
        return call_user_func_array($func, $args);
    }
```
As for the SRP i was thinking to add directly my helpers.
Thank you for the tips.

**Comment by schnittstabil** [comment]
Of course, but you have to handle the `with*` methods appropriately, e.g.:
```php
    public function withUploadedFiles(array $uploadedFiles)
    {
        $clone = clone $this;
        $clone->delegate = $this->delegate->withUploadedFiles($uploadedFiles);
        return $clone;
    }
```

**Comment by ncou** [comment]
Hum you are right, i will need to handle the with/witoutXXXX methods in a special way, even if this mean It will not be so easy and clean as i was expecting.

**Comment by Zegnat** [comment]
I personally really like [this article on `final`](https://ocramius.github.io/blog/when-to-declare-classes-final/). Just putting that here for people reading along.

For adding helper methods, I would be very tempted to do a decorator/wrapper sort of thing:

```php
class RequestHelper implements RequestInterface
{
    private $request;
    public function __construct(RequestInterface $request)
    {
        $this->request = $request;
    }
}
```

This is specifically possible because `RequestInterface` does not define a `__construct`. But yes, this does mean you end up having to manually copy over all of the other methods defined by `RequestInterface`. Sadly you can’t use `__call` as PHP forces you to implement the methods from the interface.

**Comment by designcise** [comment]
I don't see why this has to be a matter of egos, especially if so many people are requesting it and there are valid use cases for it, why not just remove the final keyword? I too, am having a huge problem with this issue. I started off by using decorator pattern, but that quickly ends up making the class too big and also, not forgetting the layers it adds on top. The other solution I came up with was to extend the Response to create stuff like JsonResponse, HtmlResponse, etc. but that's not quite possible with the use of final. Perhaps, you guys should revisit this?
