### ISSUE TITLE
separate factories project ?

### ISSUE THREAD

**Issue by ncou** [Nyholm/psr7#37]
Hi,

Very nice piece of code.
Just a silly question, and i want your insights.

why not have the factories in a separate project ? factories are not (yet) official psr specs and the fact to mix some strict psr implementation and some interop implementation in the same project seems a bit strange in my opinion.
Is it an anticipation of the standards ?

**Comment by Nyholm** [comment]
That is a fair question. 

I think they belong together since how else would you create the objects without factories :)

I am in the workgroup of psr17. And my opinion is that we are “pretty much” done. It is only the ServerRequestFactory that might change. 

I also know that interop will be compatible with httplug. I have marked the interop facotory implementations as experimental/internal.

**Comment by ncou** [comment]
good news if the factories are soon marked as PSR17, I understand better why it's in the same project, thank for your insights, even if i have already see the factories were already used in your project :-) .

by the way, do you mind if i use your psr7 library as a dependency on my "soon to be" micro-framework ? i find your libray small and clear and i like to understand the code i use.

keep up the good work.

**Comment by Nyholm** [comment]
I would be happy to. 

I do also feel that we are close to a 1.0.0 release.

**Comment by ncou** [comment]
Cool :)
